### ISSUE TITLE
Error when bad versions are present

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/genesis#119]
Currently if the version specified for a stemcell/release is specified in quotes, or a misspelling of latest,  the errors presented to the end user aren't that helpful - it says that the specified version is not present, even if it actually is.

We should probably account for this, strip quoting characters from the versions, and ensure they match some sort of version regex to bail out if they're invalid.

**Comment by norman-abramovitz** [comment]
Implementing at least in three steps

1. Stripping Quotes
1.1 Will only process single and double quotes
1.2 Will not process folding style strings (>)
1.3 Will only check that string length change is either zero or two.  Will generate an warning statement
1.4 Will not generate an error for mismatch quotes

2. latest and track processing
2.1 Will lowercase before comparison

3 Version number checking
3.1  Should release version strings be checked at all?  They can be customized through the bosh cli  and may contain development build numbers.
3.2 Should the version follow the semver specification or just x.y.z?
3.3 Will check stemcell version since it is less likely be a development build.   Will generate a warning instead of an error.

**Comment by geofffranks** [comment]
I was thinking of something more like 

```
if [[ ${VERSION} != "latest" && ${VERSION} != "track" && ${VERSION} !~ /^[.\-0-9]\+$/ ]];
  echo Bad version (expected "latest", "track", or a version string: ${VERSION}
  exit 1
fi
```

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2
