### ISSUE TITLE
Turn on curl -v when --debug is specified

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#182]
when genesis init returns a github error in a complicate network environment, we would like to see traffic details when it curls the release/pre-release tar ball

**Comment by jhunt** [comment]
We should probably call this `--trace`, and also control it via the `GENESIS_TRACE` environment variable.

**Comment by xiujiao** [comment]
Note: current genesis `--trace` shows less output compare with `--debug `when running `genesis init`. It supposes to "Even more debugging, including debugging inside called tools (like spruce and bosh" from `genesis -h`

**Comment by dennisjbell** [comment]
hmm, the code just has DEBUG AND TRACE, not GENESIS_DEBUG AND GENESIS_TRACE -- a minor but noteworthy difference.  Regarding the --trace option: Because you can specify both --trace and --debug, I think its better to put any "forwarding" debugging (ie turns on debugging output in subsequently called executables) into --trace as James suggests, and fix the description.  Alternatively, turning on --trace also turns on debug, but that's much messier leading to obscurity/confusion.

**Comment by jhunt** [comment]
`TRACE`, `GENESIS_TRACE`, whatever the variable name, curl debugging is a 'second stage' debugging effort, something I'd rather not see with just `--debug`

**Comment by jhunt** [comment]
@dennisjbell do you have commits in-flight for this one?

**Comment by jhunt** [comment]
I've got commits in-flight on this, waiting for a merge to avoid conflicts.
