### ISSUE TITLE
Discuss about how to deal with divergence between params.env, env.yml, params.bosh and params.vault

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#186]

**Comment by jhunt** [comment]
Thoughts:

1. **params.env** is still the environment name, and if it doesn't match the file name, then Geneiss should bail out. (But see below).
2. **params.vault** is always checked, and we stop inferring it from the env name.  If params.vault is not found in any part of the env file ancestor chain, Genesis should bail out.  This allows a base (global) env yaml to define it in the future if/when spruce learns how to do something like `(( sub "-" "/" params.env ))`
3. **params.bosh** - _I'm not sure what divergence we are dealing with here_.

I would also propose that we introduce a new reserved param, **params.deployment** that holds the name of the BOSH deployment, so that it can differ from the environment name.  At the end of the day, the env name is the env name, regardless of what you called it in bosh.  It would be _nice_ if they matched, but they don't have to.  Treating the deployment name as a first-class thing simplifies a lot of the code and clarifies the purpose of environment name.

(Note: I may be misunderstanding the ask here, but the original issue had no description, so I'm piecing the context together from scattered conversations happening offline).
