### ISSUE TITLE
Can genesis list its predefined templates and what deployments it was tested with?

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/genesis#33]
doing google searches to figure out if a template exists seems slightly awkward.   Knowing aws/vsphere, deployment packages and maybe releases would be nice to know in the template readme file.

**Comment by jhunt** [comment]
This is up to the author of the template, currently.  For example, the Stark & Wayne BOSH deployment template (https://github.com/starkandwayne/bosh-deployment) has sections in its README for each site, like https://github.com/starkandwayne/bosh-deployment#amazon-ec2-aws-sites

Since the template author probably also needs to convey additional parameters that template users need to set, and provide some information on the substance of the site template, I think that this is sufficient for now.
